# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Install Poetry and Deps
    init: |
      curl -sSL https://install.python-poetry.org | python3 - &&
      poetry config virtualenvs.in-project true &&
      cd crews && poetry install

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
